#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/xlattice_go
  
  rm -rf db/tmp/* msg/tmp/* 
  
  pySloc -L go cmd/ssh2pkcs8/ssh2pkcs8.go  -X *.pb.go -v $@
else
  echo "DEV_BASE is not defined"
fi
