package reg

import (
	"errors"
)

var (
	BadAttrsLine                   = errors.New("badly formed attrs line")
	BadVersion                     = errors.New("badly formated VERSION")
	CantFindClusterByID            = errors.New("cannot find cluster with this ID")
	CantFindClusterByName          = errors.New("cannot find cluster with this name")
	ClientMustHaveEndPoint         = errors.New("client must have at least one endPoint")
	ClusterMembersMustHaveEndPoint = errors.New("cluster members must have at least one endPoint")
	ClusterMustHaveTwo             = errors.New("cluster must have at least two members")
	IDAlreadyInUse                 = errors.New("ID already in use")
	IllFormedCluster               = errors.New("ill-formed cluster serialization")
	IllFormedRegCred               = errors.New("ill-formed regCred serialization")
	MissingClosingBrace            = errors.New("missing closing brace")
	MissingClusterNameOrID         = errors.New("missing cluster name or ID")
	MissingEndPointsSection        = errors.New("missing endPoints section")
	MissingMembersList             = errors.New("missing members list")
	MissingPrivateKey              = errors.New("missing private key line")
	MissingRegNodeLine             = errors.New("missing regNode line")
	MissingServerInfo              = errors.New("missing server info")
	NameAlreadyInUse               = errors.New("name already in use")
	NilCluster                     = errors.New("nil cluster argument")
	NilNode                        = errors.New("nil node argument")
	NilPrivateKey                  = errors.New("nil private key argument")
	NilRegistry                    = errors.New("nil registry argument")
	NilToken                       = errors.New("nil XLRegMsg_Token argument")
	NoNodeNoKeys                   = errors.New("no node and no keys to build one")
	RcvdInvalidMsgForState         = errors.New("invalid msg type for current state")
	TagOutOfRange                  = errors.New("message tag of of range")
	UnexpectedMsgType              = errors.New("unexpected message type")
	UnknownClient                  = errors.New("client unknown, not in registry")
	WrongNumberOfBytesInAttrs      = errors.New("wrong number of bytes in attrs")
)
