// Code generated by protoc-gen-go.
// source: p.proto
// DO NOT EDIT!

package node

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type XLatticeMsg_Cmd int32

const (
	XLatticeMsg_Hello     XLatticeMsg_Cmd = 1
	XLatticeMsg_Bye       XLatticeMsg_Cmd = 2
	XLatticeMsg_KeepAlive XLatticeMsg_Cmd = 3
	XLatticeMsg_Ack       XLatticeMsg_Cmd = 4
	XLatticeMsg_Error     XLatticeMsg_Cmd = 5
	XLatticeMsg_Get       XLatticeMsg_Cmd = 6
	XLatticeMsg_Put       XLatticeMsg_Cmd = 7
	XLatticeMsg_IHave     XLatticeMsg_Cmd = 8
)

var XLatticeMsg_Cmd_name = map[int32]string{
	1: "Hello",
	2: "Bye",
	3: "KeepAlive",
	4: "Ack",
	5: "Error",
	6: "Get",
	7: "Put",
	8: "IHave",
}
var XLatticeMsg_Cmd_value = map[string]int32{
	"Hello":     1,
	"Bye":       2,
	"KeepAlive": 3,
	"Ack":       4,
	"Error":     5,
	"Get":       6,
	"Put":       7,
	"IHave":     8,
}

func (x XLatticeMsg_Cmd) Enum() *XLatticeMsg_Cmd {
	p := new(XLatticeMsg_Cmd)
	*p = x
	return p
}
func (x XLatticeMsg_Cmd) String() string {
	return proto.EnumName(XLatticeMsg_Cmd_name, int32(x))
}
func (x XLatticeMsg_Cmd) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *XLatticeMsg_Cmd) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(XLatticeMsg_Cmd_value, data, "XLatticeMsg_Cmd")
	if err != nil {
		return err
	}
	*x = XLatticeMsg_Cmd(value)
	return nil
}

type XLatticeMsg struct {
	Op               *XLatticeMsg_Cmd `protobuf:"varint,1,opt,enum=node.XLatticeMsg_Cmd" json:"Op,omitempty"`
	MsgN             *uint64          `protobuf:"varint,2,opt" json:"MsgN,omitempty"`
	ID               []byte           `protobuf:"bytes,3,opt" json:"ID,omitempty"`
	Salt             []byte           `protobuf:"bytes,4,opt" json:"Salt,omitempty"`
	Sig              []byte           `protobuf:"bytes,5,opt" json:"Sig,omitempty"`
	YourMsgN         *uint64          `protobuf:"varint,6,opt" json:"YourMsgN,omitempty"`
	YourID           []byte           `protobuf:"bytes,7,opt" json:"YourID,omitempty"`
	ErrCode          *uint64          `protobuf:"varint,8,opt" json:"ErrCode,omitempty"`
	ErrDesc          *string          `protobuf:"bytes,9,opt" json:"ErrDesc,omitempty"`
	Hash             []byte           `protobuf:"bytes,10,opt" json:"Hash,omitempty"`
	Payload          []byte           `protobuf:"bytes,11,opt" json:"Payload,omitempty"`
	CommsKey         []byte           `protobuf:"bytes,12,opt" json:"CommsKey,omitempty"`
	SigKey           []byte           `protobuf:"bytes,13,opt" json:"SigKey,omitempty"`
	MyEnd            *string          `protobuf:"bytes,14,opt" json:"MyEnd,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *XLatticeMsg) Reset()         { *m = XLatticeMsg{} }
func (m *XLatticeMsg) String() string { return proto.CompactTextString(m) }
func (*XLatticeMsg) ProtoMessage()    {}

func (m *XLatticeMsg) GetOp() XLatticeMsg_Cmd {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return 0
}

func (m *XLatticeMsg) GetMsgN() uint64 {
	if m != nil && m.MsgN != nil {
		return *m.MsgN
	}
	return 0
}

func (m *XLatticeMsg) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *XLatticeMsg) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *XLatticeMsg) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *XLatticeMsg) GetYourMsgN() uint64 {
	if m != nil && m.YourMsgN != nil {
		return *m.YourMsgN
	}
	return 0
}

func (m *XLatticeMsg) GetYourID() []byte {
	if m != nil {
		return m.YourID
	}
	return nil
}

func (m *XLatticeMsg) GetErrCode() uint64 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *XLatticeMsg) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *XLatticeMsg) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *XLatticeMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *XLatticeMsg) GetCommsKey() []byte {
	if m != nil {
		return m.CommsKey
	}
	return nil
}

func (m *XLatticeMsg) GetSigKey() []byte {
	if m != nil {
		return m.SigKey
	}
	return nil
}

func (m *XLatticeMsg) GetMyEnd() string {
	if m != nil && m.MyEnd != nil {
		return *m.MyEnd
	}
	return ""
}

func init() {
	proto.RegisterEnum("node.XLatticeMsg_Cmd", XLatticeMsg_Cmd_name, XLatticeMsg_Cmd_value)
}
